# Generated by Django 4.1.4 on 2023-01-05 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Best',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Год лучшее')),
                ('content', models.TextField(blank=True, verbose_name='Описание года')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
        ),
        migrations.CreateModel(
            name='Janr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Жанр игры')),
                ('content', models.TextField(blank=True, verbose_name='Описание жанра')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название игры')),
                ('content', models.TextField(blank=True, verbose_name='Описание игры')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('buy', models.CharField(max_length=255, verbose_name='Купить игру')),
                ('best', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pixel.best', verbose_name='Лучшая')),
                ('janr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pixel.janr', verbose_name='Жанр')),
            ],
        ),
    ]
