# Generated by Django 4.1.4 on 2023-01-06 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='best',
            options={'verbose_name': 'Лучшее', 'verbose_name_plural': 'Лучшее'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Игры', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='janr',
            options={'verbose_name': 'Жанры игр', 'verbose_name_plural': 'Жанры игр'},
        ),
        migrations.AlterField(
            model_name='game',
            name='best',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pixel.best', verbose_name='Лучшая'),
        ),
        migrations.AlterField(
            model_name='game',
            name='janr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pixel.janr', verbose_name='Жанр'),
        ),
    ]
