# Generated by Django 4.1.4 on 2023-01-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0002_alter_best_options_alter_game_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pixel',
            field=models.BooleanField(default=True),
        ),
    ]
